# Generated by Django 3.2 on 2021-05-16 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dordoishopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dordoishop',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес:'),
        ),
        migrations.AlterField(
            model_name='dordoishop',
            name='logo',
            field=models.ImageField(upload_to='dordoishop_logo/', verbose_name='Ваш контейнер или фото вашего ассортимента?'),
        ),
        migrations.AlterField(
            model_name='dordoishop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Опишите каким продовольствием занимаетесь?'),
        ),
        migrations.AlterField(
            model_name='dordoishop',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Ваш номер:'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.IntegerField(default=0)),
                ('dordoishop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dordoishopapp.dordoishop')),
            ],
        ),
    ]
